### ISSUE TITLE
Way to avoid waiting in broadcast() when there are only inactive receivers

### ISSUE THREAD

**Issue by madadam** [smol-rs/async-broadcast#25]
Currently `Sender::broadcast` waits when called while there are only inactive receivers. This is not always desirable. For example, I might not care about sending notifications when there is no one listening for them, but I might still want to keep one `InactiveReceiver` around in order to dynamically create `Receiver`s at any later time.

My current workaround is to check `Sender::receiver_count` before calling `Sender::broadcast`, but this is prone to race condition because all receivers might get deactivated in between the check and the `broadcast` call.  Is there a better way to do this?

Possible improvements to support this use case:
1. Add a  new config option, similar to `set_overflow`, to control the sending behaviour when there are only inactive receivers.
2. Add `fn subscribe(&self) -> Receiver` to `Sender` which would return a `Receiver`. Then one wouldn't need to keep the inactive receiver and would still be able to create more receivers.

**Comment by zeenix** [comment]
> * Add `fn subscribe(&self) -> Receiver` to `Sender` which would return a `Receiver`. Then one wouldn't need to keep the inactive receiver and would still be able to create more receivers.

I like this one the best as there may be other use cases of creating a Receiver from a Sender. Also it avoids complicating the behaviour of `Sender::broadcast` more than it already is. As for the naming, is there any prior art here to draw from? Otherwise `subscribe` is fine I guess.

**Comment by madadam** [comment]
> As for the naming, is there any prior art here to draw from

Yes, for example tokio uses it: https://docs.rs/tokio/1.15.0/tokio/sync/broadcast/struct.Sender.html#method.subscribe.

One potential issue with it is this: say initially we have at least one sender and one receiver. Then all the receivers are dropped. This "closes" the channel. Calling `subscribe` on the sender afterwards would have to "reopen" the channel somehow. Not that familiar with the internals of this crate, but would that be easy to do?

**Comment by zeenix** [comment]
> Then all the receivers are dropped. This "closes" the channel.

Not if you keep an Inactive receiver around. :)

**Comment by yoshuawuyts** [comment]
A third option which I haven't seen mentioned yet would be to follow the same pattern as `std::arc::{Arc, Weak}`. You can convert an `Arc` to a `Weak` and vice-versa, but the `Weak` version will never hold onto the data. In this case we could have a concept of a `WeakReceiver` [^name] which cannot receive any messages, and cannot hold the channel open. But it can be used to construct a new `Receiver` from.

[^name]: Name subject to change. `Inactive` or `InactiveReceiver` could be alternative options.

We would likely need to distinguish in `SendError` between:
- "there are no receivers available" (no receivers, possibly weak receivers)
- "channel has been closed" (no receivers, no weak receivers)

If a `Sender` can always be converted to a receiver, there might always potentially be a receiver available. This approach has the benefit that we can always tell whether the channel is closed, or there temporarily aren't any receivers available. But the downside is that we would be introducing a new type. And potentially we may want to do the same for `Sender` as well; introducing a `WeakSender` type.

The main question to ask here is probably: "Do we care about knowing whether something is permanently closed or just temporarily?" I'm not sure, but I figured I'd raise it.

**Comment by zeenix** [comment]
> 1. Name subject to change. `Inactive` or `InactiveReceiver` could be alternative options. [leftwards_arrow_with_hook](#user-content-fnref-name-46fe6763e71be8aa4f6514e2d4fce5ad)

We already have `InactiveReceiver` that serves a very similar purpose (i-e to keep the channel open while there are no active receivers). The only diff with what you are proposing here is that when overflow-mode is not enabled, `Sender::broadcast` waits for an active receiver to be available.

**Comment by madadam** [comment]
> Not if you keep an Inactive receiver around. :)

But that brings us back to my original issue: if there is an inactive receiver and no active ones then calling `broadcast` would wait which is what I wanted to avoid. The idea with `subscribe` was that I would only keep a `Sender` around so calling `broadcast` would immediately fail without waiting but I would still be able to create receivers later. But I think this would imply that `subscribe` must be able to reopen an already closed channel. That sounds reasonable to me but others might have different opinions. Also, there are at least two cases: when the channel gets closed due to all receivers (active or inactive) being dropped, then should calling `subscribe` reopen it? I'd say yes in this case. However, if the channel was closed explicitly by calling `close`, should `subscribe` also reopen it? I'm not so sure on this one. 

> I'm afraid you'll have to provide a PR for this

I'd be happy to, once we agree on the approach.

**Comment by zeenix** [comment]
> > Not if you keep an Inactive receiver around. :)
> 
> But that brings us back to my original issue: if there is an inactive receiver and no active ones then calling broadcast would wait which is what I wanted to avoid. 

You won't use `broadcast` but rather `try_broadcast` and if the error is `TrySendError::Inactive`, you use `subscribe` to change that. The channel won't be closed because you've an inactive receiver around.

W/o `subscribe`, you could also keep a `Receiver` around, along with your `Sender` in the first place and read from it each time you broadcast. That way, `Sender` won't ever wait for inactivity and if there are no other active receivers at the time, the message will basically get dropped. But that's not as nice as an API provided by async-broadcast to help you a bit here.

Regardless, I think providing the `subscribe` method you suggested would be good to have anyway. I wouldn't want to complicate the implementation with reopening the channel, though unless my try_broadcast suggestion above won't work(?).

**Comment by zeenix** [comment]
> > I'm afraid you'll have to provide a PR for this
> 
> I'd be happy to, once we agree on the approach.

:+1:

**Comment by madadam** [comment]
> You won't use broadcast but rather try_broadcast and if the error is TrySendError::Inactive, you use subscribe to change that. The channel won't be closed because you've an inactive receiver around.

This is still not as nice as if `subscribe` could reopen a closed channel because then I wouldn't even need to create this temporary receiver. But I think I can work with it. So I'm OK to take this approach and create the PR. Just one more question: should calling `subscribe` on a closed channel return an error?

**Comment by zeenix** [comment]
> > You won't use broadcast but rather try_broadcast and if the error is TrySendError::Inactive, you use subscribe to change that. The channel won't be closed because you've an inactive receiver around.
> 
> This is still not as nice as if `subscribe` could reopen a closed channel because then I wouldn't even need to create this temporary receiver.

I see your point. I'm a just a bit scared of unforeseen complications coming from reopening a closed channel. Maybe I'm being paranoid. :) I see that [tokio's impl](https://docs.rs/tokio/latest/tokio/sync/broadcast/struct.Sender.html#method.subscribe) doesn't do that but they also don't close the channel on all receivers dropping. Maybe it'd be fine to re-open the channel, as per your suggestion and just ensure it's an atomic operation.

**Comment by zeenix** [comment]
Doesn't look like this is going anywhere. Feel free to re-open.
