### ISSUE TITLE
Consider switching from parking_lot back to std::sync

### ISSUE THREAD

**Issue by mwcampbell** [smol-rs/async-broadcast#37]
Rationale: The std::sync primitives got more efficient on most platforms in the past year. Even on platforms where parking_lot is still faster (at least in some cases), such as macOS, there are tradeoffs, such as parking_lot's global hash table. In any case, being able to eliminate the dependency is appealing.

**Comment by zeenix** [comment]
I'm all for it. Could you provide a PR?

**Comment by BratSinot** [comment]
> Rationale: The std::sync primitives got more efficient on most platforms in the past year. Even on platforms where parking_lot is still faster (at least in some cases), such as macOS, there are tradeoffs, such as parking_lot's global hash table. In any case, being able to eliminate the dependency is appealing.

`parking_lot` have [no poisoning](https://docs.rs/parking_lot/latest/parking_lot/type.RwLock.html#differences-from-the-standard-library-rwlock):
> No poisoning, the lock is released normally on panic.

**Comment by zeenix** [comment]
> `parking_lot` have [no poisoning](https://docs.rs/parking_lot/latest/parking_lot/type.RwLock.html#differences-from-the-standard-library-rwlock):

I wonder if that really affects/helps us. All the locking is done internally so is there a chance of a thread panicking while holding the lock?

**Comment by BratSinot** [comment]
> I wonder if that really affects/helps us. All the locking is done internally so is there a chance of a thread panicking while holding the lock?

Hm.., may be in case of polling future from `pub fn broadcast(&self, msg: T) -> Send<'_, T> `?..

**Comment by zeenix** [comment]
> Hm.., may be in case of polling future from `pub fn broadcast(&self, msg: T) -> Send<'_, T> `?..

Sorry, not sure I follow. The future impl doesn't keep the lock guard around.

**Comment by BratSinot** [comment]
> The future impl doesn't keep the lock guard around.

Hm, right.

**Comment by mwcampbell** [comment]
Belated thanks for changing this. Now AccessKit no longer has any transitive dependency on parking_lot on any platform.
